/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_clzhang_helloworld_JniWrapper */

#ifndef _Included_com_example_clzhang_helloworld_JniWrapper
#define _Included_com_example_clzhang_helloworld_JniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_clzhang_helloworld_JniWrapper
 * Method:    messageFromNativeCode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_clzhang_helloworld_JniWrapper_messageFromNativeCode (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
